### ISSUE TITLE
decouple Aserver/Arecorder and pyaudio and introduce backends

### ISSUE THREAD

**Issue by aleneum** [interactive-sonification/pya#13]
I have a suggestion concerning Aserver/Arecorder. I would like to add pyaudio-agnostic support to Aserver at least to use `pya` in a remote Jupyter Notebook via Binder. Right now `Aserver` and `Arecorder` are tightly coupled to `pyaudio`. This also makes testing more complicated than it needs to be.

If both classes had a `backend` parameter one could provide a collection of different in- and output channels (e.g. `PyAudioPlayer`, `JupyterPlayer`, `FFmpegWriter`, `NullWriter`, `NumpyWriter` for `Aserver` and `PyAudioRecorder`, `JupyterRecorder`, `FFmpegReader`, `NumpyReader` for `Arecorder`) and make both classes way more versatile. The default value must be `pyaudio` of course.

```python
s = Aserver(bs=1024)
f = Aserver(bs=1024, backend=FileWriter(directory='./out', format='wav'))
j = Aserver(bs=1024, backend=JupyterWidget(autoplay=True))
# ...
atone.play(server=s)
# atone sounds AMAZING, save it
atone.play(server=f)
# this creates a playable html audio element right below the executing Jupyter Cell
atone.play(server=j)
# for remote notebooks just do
Aserver.default = j
# now every play will create an interactive Jupyter widget
atone.play()
# testing models with previously recorded files
ar_test = Arecorder(channels=1, backend=FFmpegReader(directory="in/*.wav", realtime=True, split_signals=False)).boot()
# reads samples from globbed files (in realtime or afap), as single Asig (`split_signals=False`; same behaviour as `pyaudio`) or a new Asig for each new file (`split_signals=True`).
ar_test.record()
ar_test.stop()
# process all the recordings
ar = ar_test
while len(ar.recordings):
    magic_model.process(ar.recordings.pop(0))  # process data FIFO 
# model_magic works good, now lets get real
ar_live = Arecorder(channels=1).boot()
ar = ar_live
```

**Comment by thomas-hermann** [comment]
That (introduction of backends) is an excellent idea. There are some points, though:

- Aserver usually needs booting and then _continuously_ streams buffers/blocks of data to the/an output. In contrast, your examples invoke it in a way that audio data would only be processed (and separately) when using play(). Play then also won't be able to use the onset.

- Before introducing Aserver we had a play() which created a stream just for that play alone, yet that doesn't scale well for hundreds of play()s at dedicated onsets (i.e. play(onset=timestamp)). That was my original motivation for Aserver...

- Thought: we could, however, introduce additional singular (non-streamed) methods specifically for individual audio output (e.g. titled play1(), name to be improved), for which the above backend use cases would work better, this could be available for Aserver even if not booted, or alternatively that could be for another class (tentative name Aplayer) the play() function, which would always create the connection to the selected backend...

- As to Aserver vs. Arecorder: I discussed with Jiajun what the best way would be to proceed: Ideally, Aserver could grow into a more general class (Audiomanager) which allows both (and simultaneous) inputs and outputs, (similar to sc3synth, moving to C, enabling blockwise input monitoring on outputs, etc.) and the current Aserver would become Aplayer... 

- I currently lack clarity about the most robust/clean way to proceed and appreciate any thoughts and ideas and suggestions :-)

**Comment by aleneum** [comment]
> Aserver usually needs booting and then continuously streams buffers/blocks of data to the/an output. In contrast, your examples invoke it in a way that audio data would only be processed (and separately) when using play().

I illustrate a use case based on the public pya API and I am fully aware that this is not feature complete. Right now I haven't made -- or let's say intended to make -- statements about how different backends process input. This might be a separate discussion. 

> Play then also won't be able to use the onset.

This is debatable. I don't see why this should not work with a `FileWriter` for instance. 

> Thought: we could, however, introduce additional singular (non-streamed) methods specifically ...

I'd prefer a transparent solution where backend access is unified and it is the backend's concern to deal with data from Aserver/Aplayer.

>  As to Aserver vs. Arecorder: I discussed with Jiajun what the best way would be to proceed: Ideally, Aserver could grow into a more general class (Audiomanager) which allows both (and simultaneous) inputs and outputs,

Refactoring concerns sounds like a good plan. Aplayer/Arecorder is more consistent. A manager could then even use multiple streams (with differing backends) simultaneously.

>  (similar to sc3synth, moving to C, enabling blockwise input monitoring on outputs, etc.) and the current Aserver would become Aplayer...

Does that mean you want to port things to Cython/Swig? If (all) A* classes should become C bindings however, writing extension becomes more difficult of course. Nevertheless backends will probably operate on passed (numpy-based) data buffers. It might even be possible to write Python as well as C extensions.

**Comment by thomas-hermann** [comment]
Thanks @aleneum, for the good arguments!

> I'd like to discuss corner cases where you think a backend approach might fall short.

I think (the introduction of) backends is an ideal approach to naturally implement the diverse extensions you proposed. I can't think of any shortcomings. But looking again at your initial code snippet makes me more aware that there are two fundamentally different use cases (to my opinion):

- stream processing, and 
- event-based processing.

At this time, play() allows to weave an event (Asig) into the stream, dissolving its begin and end, for a jupyter widget, it would remain a distinct event, interactable via the widget.

> I'd prefer a transparent solution where backend access is unified and it is the backend's concern to deal with data from Aserver/Aplayer.

I am with you here, but nonetheless think that there are arguments to augment Aserver() to deal both with events and streams natively. Backends would then offer support for what they can, either event-based processing or the stream processing, or both. I see also utility for event-based processing with backend pyaudio, as it allows to play audio independent of a running server (which at this time sometimes creates chopping audio, depending on block size).

> Refactoring concerns sounds like a good plan. Aplayer/Arecorder is more consistent. A manager could then even use multiple streams (with differing backends) simultaneously.

looking forward to hear your advice, maybe let's have a coffee with Jiajun at some time at CITEC...

> Does that mean you want to port things to Cython/Swig? If (all) A* classes should become C bindings however, writing extension becomes more difficult of course. 

no, probably only time critical stuff: the current python-based Aserver._play_callback() has substantial risk of audio chopping, particularly at small blocksize, probably due to too many python function calls and GIL - motivating the search for a more robust, low-level, multi-core-embracing solution - but this is probably a different issue and discussion. Concerning backends, I would see that rather an issue for specific backend implementations, e.g. the pyaudio..., than a general issue for Aserver.

**Comment by aleneum** [comment]
closing this since backends have been implemented and further feature discussions will be continued in separate issues
