### ISSUE TITLE
Ugen, numpy sine array result in different precision on different environment

### ISSUE THREAD

**Issue by wiccy46** [interactive-sonification/pya#50]
This only break on Python3.7 at Ubuntu latest. With a sine wave generated having a different precision than other environment. Can also reproduce on Fedora 36. This needs to be investigated why difference happened. 

Test log:
```
    def test_sine(self):
        sine = Ugen().sine(freq=200, amp=0.5, dur=1.0, sr=44100 // 2, channels=2)
        self.assertEqual(44100 // 2, sine.sr)
>       self.assertAlmostEqual(0.5, np.max(sine.sig), places=6)
E       AssertionError: 0.5 != 0.49999684 within 6 places (3.159046173095703e-06 difference)
```

**Comment by thomas-hermann** [comment]
The reason for this "break" is that after correcting Ugen.sine by setting endpoint=False in the linspace, the periodicity is now correct on sampling a 200 Hz signal, (the period is 22050/200=110.25, in turn the waveform repeats itself orderly, leading to the sampling time to miss systematically the location where the sine maxes. Before, the np.linspace created time locations at times multiple of 1 second / 22049 (because endpoint was true). Hence, every sine wave of 200 Hz was sampled at slightly different locations, so that apparently it happened that in one of the 200 sine waves on the 1s sound, a location close enough was hit to give sine(time)=1, (due to amp=0.5 resulting in the max(sig)=0.5). 
The 'break' shows that the test should be improved, e.g. by using a frequency so that the sine function is in fact called so that it delivers a maximum, e.g. freq = 44100/16 = 2756.25 Hz will do it: Then a sine wave is sampled with 8 samples, two of them hitting the zero crossings, one each for max and min locatio and the others in between. The test then works also with dur=0.001, saving 99.9% of energy, making the test more sustainable.

**Comment by wiccy46** [comment]
Mark as solved.

**Comment by thomas-hermann** [comment]
actually the issue was probably not 'different precision', I don't know why it should work different on different platforms..
